### ISSUE TITLE
Cannot find module 'auto-launch'

### ISSUE THREAD

**Issue by benjcallaghan** [Teamwork/node-auto-launch#67]
- The target platform(s) the problem occurs on (Linux, Mac, Mac App Store, and or Windows):
Mac
- Node version (run `node -v`): 
6.11.2
- auto-launch version:
5.0.2
- Are you using NW.js or Electron?
Electron and pure Node
  - If so, which version? 
1.7.9
  - If you're using Electron, are you using auto-launch from the main process or a renderer process?
Main process
- Can you reproduce this with a simple Hello World example app?
Yes
- If needs be, would you be able to provide us with a simple app (as simple as possible) which reproduces the problem?

Here is a minimal example that produces the error:
```javascript
var AutoLaunch = require('auto-launch');
```

---

After installing auto-launch@5.0.2, I am unable to `require` the module. Each time I run, I get the following error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'auto-launch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/benj/Projects/test/index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Upon further investigation, I can see that node_modules/auto-launch has no dist folder, nor does it have any JavaScript files of any kind. It looks as if the files were missing from the published package. This does not occur on version 5.0.1.

**Comment by BennZoid** [comment]
I am currently having the same issue while trying to build [riot](https://github.com/vector-im/riot-web) with 5.0.2 on a linux machine.  Can confirm that reverting to auto-launch@5.0.1 fixes the issue for me as well.

**Comment by vaidyaanand** [comment]
Hello I have done 
`npm install --save auto-launch`

when I run `npm start`

I am getting following error 
```
App threw an error during load
Error: Cannot find module 'auto-launch'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\anand\learning\node\clonedApp\simple-samples\activity-monitor\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\anand\learning\node\clonedApp\simple-samples\activity-monitor\app.js:6:18)
    at Object.<anonymous> (C:\anand\learning\node\clonedApp\simple-samples\activity-monitor\app.js:87:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by Nikitikitavi** [comment]
Hi! I had same error with version 5.0.2. 
Roll back to version 5.0.1 works for me until it will be fixed in new version. 

Actually looks like last version not installing at all, it has only package.json file inside with READMI and LICENSE after installing.

**Comment by vaidyaanand** [comment]
Sure Thanks, I have rollback to the previous version and it is working fine.

**Comment by wmin0** [comment]
package 5.0.2 didn't include dist directory.

**Comment by adam-lynch** [comment]
Argh... I've just published 5.0.3. Should be fine now.

**Comment by fengerzh** [comment]
Even 5.0.5 did not solve my problem. I can `npm run start`, but after I package it to exe, it won't work. So what I did is: `cd node_modules/auto-launch`, and `copy dist\*.* ./`, then package, and everything works.

**Comment by sunmaobin** [comment]
@fengerzh the same to you ,but the method is not work for me ~~~~

**Comment by shklyarik** [comment]
May be exist any other solutions?
